# Print an optspec for argparse to handle cmd's options that are independent of any subcommand.
function __fish_rift_cli_global_optspecs
	string join \n h/help
end

function __fish_rift_cli_needs_command
	# Figure out if the current invocation already has a command.
	set -l cmd (commandline -opc)
	set -e cmd[1]
	argparse -s (__fish_rift_cli_global_optspecs) -- $cmd 2>/dev/null
	or return
	if set -q argv[1]
		# Also print the command, so this can be used to figure out what it is.
		echo $argv[1]
		return 1
	end
	return 0
end

function __fish_rift_cli_using_subcommand
	set -l cmd (__fish_rift_cli_needs_command)
	test -z "$cmd"
	and return 1
	contains -- $cmd[1] $argv
end

complete -c rift-cli -n "__fish_rift_cli_needs_command" -s h -l help -d 'Print help'
complete -c rift-cli -n "__fish_rift_cli_needs_command" -f -a "query" -d 'Query information from rift'
complete -c rift-cli -n "__fish_rift_cli_needs_command" -f -a "execute" -d 'Execute commands in rift'
complete -c rift-cli -n "__fish_rift_cli_needs_command" -f -a "subscribe" -d 'Event subscription commands'
complete -c rift-cli -n "__fish_rift_cli_needs_command" -f -a "service" -d 'Manage the launchd service for rift'
complete -c rift-cli -n "__fish_rift_cli_needs_command" -f -a "verify"
complete -c rift-cli -n "__fish_rift_cli_needs_command" -f -a "help" -d 'Print this message or the help of the given subcommand(s)'
complete -c rift-cli -n "__fish_rift_cli_using_subcommand query; and not __fish_seen_subcommand_from workspaces windows displays window applications layout workspace-layout metrics help" -s h -l help -d 'Print help'
complete -c rift-cli -n "__fish_rift_cli_using_subcommand query; and not __fish_seen_subcommand_from workspaces windows displays window applications layout workspace-layout metrics help" -f -a "workspaces" -d 'List virtual workspaces (optionally for a specific MacOS space)'
complete -c rift-cli -n "__fish_rift_cli_using_subcommand query; and not __fish_seen_subcommand_from workspaces windows displays window applications layout workspace-layout metrics help" -f -a "windows" -d 'List windows (optionally filtered by space)'
complete -c rift-cli -n "__fish_rift_cli_using_subcommand query; and not __fish_seen_subcommand_from workspaces windows displays window applications layout workspace-layout metrics help" -f -a "displays" -d 'List connected displays'
complete -c rift-cli -n "__fish_rift_cli_using_subcommand query; and not __fish_seen_subcommand_from workspaces windows displays window applications layout workspace-layout metrics help" -f -a "window" -d 'Get information about a specific window'
complete -c rift-cli -n "__fish_rift_cli_using_subcommand query; and not __fish_seen_subcommand_from workspaces windows displays window applications layout workspace-layout metrics help" -f -a "applications" -d 'List running applications'
complete -c rift-cli -n "__fish_rift_cli_using_subcommand query; and not __fish_seen_subcommand_from workspaces windows displays window applications layout workspace-layout metrics help" -f -a "layout" -d 'Get layout state for a space'
complete -c rift-cli -n "__fish_rift_cli_using_subcommand query; and not __fish_seen_subcommand_from workspaces windows displays window applications layout workspace-layout metrics help" -f -a "workspace-layout" -d 'Get workspace layout-engine mode(s)'
complete -c rift-cli -n "__fish_rift_cli_using_subcommand query; and not __fish_seen_subcommand_from workspaces windows displays window applications layout workspace-layout metrics help" -f -a "metrics" -d 'Get performance metrics'
complete -c rift-cli -n "__fish_rift_cli_using_subcommand query; and not __fish_seen_subcommand_from workspaces windows displays window applications layout workspace-layout metrics help" -f -a "help" -d 'Print this message or the help of the given subcommand(s)'
complete -c rift-cli -n "__fish_rift_cli_using_subcommand query; and __fish_seen_subcommand_from workspaces" -l space-id -r
complete -c rift-cli -n "__fish_rift_cli_using_subcommand query; and __fish_seen_subcommand_from workspaces" -s h -l help -d 'Print help'
complete -c rift-cli -n "__fish_rift_cli_using_subcommand query; and __fish_seen_subcommand_from windows" -l space-id -r
complete -c rift-cli -n "__fish_rift_cli_using_subcommand query; and __fish_seen_subcommand_from windows" -s h -l help -d 'Print help'
complete -c rift-cli -n "__fish_rift_cli_using_subcommand query; and __fish_seen_subcommand_from displays" -s h -l help -d 'Print help'
complete -c rift-cli -n "__fish_rift_cli_using_subcommand query; and __fish_seen_subcommand_from window" -s h -l help -d 'Print help'
complete -c rift-cli -n "__fish_rift_cli_using_subcommand query; and __fish_seen_subcommand_from applications" -s h -l help -d 'Print help'
complete -c rift-cli -n "__fish_rift_cli_using_subcommand query; and __fish_seen_subcommand_from layout" -s h -l help -d 'Print help'
complete -c rift-cli -n "__fish_rift_cli_using_subcommand query; and __fish_seen_subcommand_from workspace-layout" -l space-id -r
complete -c rift-cli -n "__fish_rift_cli_using_subcommand query; and __fish_seen_subcommand_from workspace-layout" -l workspace-id -r
complete -c rift-cli -n "__fish_rift_cli_using_subcommand query; and __fish_seen_subcommand_from workspace-layout" -s h -l help -d 'Print help'
complete -c rift-cli -n "__fish_rift_cli_using_subcommand query; and __fish_seen_subcommand_from metrics" -s h -l help -d 'Print help'
complete -c rift-cli -n "__fish_rift_cli_using_subcommand query; and __fish_seen_subcommand_from help" -f -a "workspaces" -d 'List virtual workspaces (optionally for a specific MacOS space)'
complete -c rift-cli -n "__fish_rift_cli_using_subcommand query; and __fish_seen_subcommand_from help" -f -a "windows" -d 'List windows (optionally filtered by space)'
complete -c rift-cli -n "__fish_rift_cli_using_subcommand query; and __fish_seen_subcommand_from help" -f -a "displays" -d 'List connected displays'
complete -c rift-cli -n "__fish_rift_cli_using_subcommand query; and __fish_seen_subcommand_from help" -f -a "window" -d 'Get information about a specific window'
complete -c rift-cli -n "__fish_rift_cli_using_subcommand query; and __fish_seen_subcommand_from help" -f -a "applications" -d 'List running applications'
complete -c rift-cli -n "__fish_rift_cli_using_subcommand query; and __fish_seen_subcommand_from help" -f -a "layout" -d 'Get layout state for a space'
complete -c rift-cli -n "__fish_rift_cli_using_subcommand query; and __fish_seen_subcommand_from help" -f -a "workspace-layout" -d 'Get workspace layout-engine mode(s)'
complete -c rift-cli -n "__fish_rift_cli_using_subcommand query; and __fish_seen_subcommand_from help" -f -a "metrics" -d 'Get performance metrics'
complete -c rift-cli -n "__fish_rift_cli_using_subcommand query; and __fish_seen_subcommand_from help" -f -a "help" -d 'Print this message or the help of the given subcommand(s)'
complete -c rift-cli -n "__fish_rift_cli_using_subcommand execute; and not __fish_seen_subcommand_from window workspace layout config mission-control display save-and-exit debug serialize toggle-space-activated show-timing help" -s h -l help -d 'Print help'
complete -c rift-cli -n "__fish_rift_cli_using_subcommand execute; and not __fish_seen_subcommand_from window workspace layout config mission-control display save-and-exit debug serialize toggle-space-activated show-timing help" -f -a "window" -d 'Window management commands'
complete -c rift-cli -n "__fish_rift_cli_using_subcommand execute; and not __fish_seen_subcommand_from window workspace layout config mission-control display save-and-exit debug serialize toggle-space-activated show-timing help" -f -a "workspace" -d 'Virtual workspace commands'
complete -c rift-cli -n "__fish_rift_cli_using_subcommand execute; and not __fish_seen_subcommand_from window workspace layout config mission-control display save-and-exit debug serialize toggle-space-activated show-timing help" -f -a "layout" -d 'Layout commands'
complete -c rift-cli -n "__fish_rift_cli_using_subcommand execute; and not __fish_seen_subcommand_from window workspace layout config mission-control display save-and-exit debug serialize toggle-space-activated show-timing help" -f -a "config" -d 'Configuration management commands'
complete -c rift-cli -n "__fish_rift_cli_using_subcommand execute; and not __fish_seen_subcommand_from window workspace layout config mission-control display save-and-exit debug serialize toggle-space-activated show-timing help" -f -a "mission-control" -d 'Mission control commands'
complete -c rift-cli -n "__fish_rift_cli_using_subcommand execute; and not __fish_seen_subcommand_from window workspace layout config mission-control display save-and-exit debug serialize toggle-space-activated show-timing help" -f -a "display" -d 'Display/mouse commands'
complete -c rift-cli -n "__fish_rift_cli_using_subcommand execute; and not __fish_seen_subcommand_from window workspace layout config mission-control display save-and-exit debug serialize toggle-space-activated show-timing help" -f -a "save-and-exit" -d 'Save current state and exit rift'
complete -c rift-cli -n "__fish_rift_cli_using_subcommand execute; and not __fish_seen_subcommand_from window workspace layout config mission-control display save-and-exit debug serialize toggle-space-activated show-timing help" -f -a "debug" -d 'Print layout tree debugging output in the running rift instance'
complete -c rift-cli -n "__fish_rift_cli_using_subcommand execute; and not __fish_seen_subcommand_from window workspace layout config mission-control display save-and-exit debug serialize toggle-space-activated show-timing help" -f -a "serialize" -d 'Serialize and print runtime state'
complete -c rift-cli -n "__fish_rift_cli_using_subcommand execute; and not __fish_seen_subcommand_from window workspace layout config mission-control display save-and-exit debug serialize toggle-space-activated show-timing help" -f -a "toggle-space-activated" -d 'Toggle whether the current space is managed by rift'
complete -c rift-cli -n "__fish_rift_cli_using_subcommand execute; and not __fish_seen_subcommand_from window workspace layout config mission-control display save-and-exit debug serialize toggle-space-activated show-timing help" -f -a "show-timing" -d 'Show timing metrics'
complete -c rift-cli -n "__fish_rift_cli_using_subcommand execute; and not __fish_seen_subcommand_from window workspace layout config mission-control display save-and-exit debug serialize toggle-space-activated show-timing help" -f -a "help" -d 'Print this message or the help of the given subcommand(s)'
complete -c rift-cli -n "__fish_rift_cli_using_subcommand execute; and __fish_seen_subcommand_from window" -s h -l help -d 'Print help'
complete -c rift-cli -n "__fish_rift_cli_using_subcommand execute; and __fish_seen_subcommand_from window" -f -a "next" -d 'Focus the next window'
complete -c rift-cli -n "__fish_rift_cli_using_subcommand execute; and __fish_seen_subcommand_from window" -f -a "prev" -d 'Focus the previous window'
complete -c rift-cli -n "__fish_rift_cli_using_subcommand execute; and __fish_seen_subcommand_from window" -f -a "focus" -d 'Move focus in a direction'
complete -c rift-cli -n "__fish_rift_cli_using_subcommand execute; and __fish_seen_subcommand_from window" -f -a "toggle-float" -d 'Toggle window floating state'
complete -c rift-cli -n "__fish_rift_cli_using_subcommand execute; and __fish_seen_subcommand_from window" -f -a "toggle-fullscreen" -d 'Toggle fullscreen mode (fills the whole screen, ignores outer gaps)'
complete -c rift-cli -n "__fish_rift_cli_using_subcommand execute; and __fish_seen_subcommand_from window" -f -a "toggle-fullscreen-within-gaps" -d 'Toggle fullscreen within configured outer gaps (respects outer gaps / fills tiling area)'
complete -c rift-cli -n "__fish_rift_cli_using_subcommand execute; and __fish_seen_subcommand_from window" -f -a "resize-grow" -d 'Grow the current window size (increments by ~5%)'
complete -c rift-cli -n "__fish_rift_cli_using_subcommand execute; and __fish_seen_subcommand_from window" -f -a "resize-shrink" -d 'Shrink the current window size (decrements by ~5%)'
complete -c rift-cli -n "__fish_rift_cli_using_subcommand execute; and __fish_seen_subcommand_from window" -f -a "resize-by" -d 'Resize the selected window by a fractional amount. - Pass a signed floating value: positive to grow, negative to shrink. - The value is a fraction of the current size (e.g. `0.05` = 5%). Examples: rift-cli execute window resize-by --amount 0.05    # grow by 5% rift-cli execute window resize-by --amount -0.10   # shrink by 10%'
complete -c rift-cli -n "__fish_rift_cli_using_subcommand execute; and __fish_seen_subcommand_from window" -f -a "close" -d 'Close a window by window server identifier'
complete -c rift-cli -n "__fish_rift_cli_using_subcommand execute; and __fish_seen_subcommand_from window" -f -a "add-scratchpad"
complete -c rift-cli -n "__fish_rift_cli_using_subcommand execute; and __fish_seen_subcommand_from window" -f -a "toggle-scratchpad"
complete -c rift-cli -n "__fish_rift_cli_using_subcommand execute; and __fish_seen_subcommand_from window" -f -a "help" -d 'Print this message or the help of the given subcommand(s)'
complete -c rift-cli -n "__fish_rift_cli_using_subcommand execute; and __fish_seen_subcommand_from workspace" -s h -l help -d 'Print help'
complete -c rift-cli -n "__fish_rift_cli_using_subcommand execute; and __fish_seen_subcommand_from workspace" -f -a "next" -d 'Switch to next workspace'
complete -c rift-cli -n "__fish_rift_cli_using_subcommand execute; and __fish_seen_subcommand_from workspace" -f -a "prev" -d 'Switch to previous workspace'
complete -c rift-cli -n "__fish_rift_cli_using_subcommand execute; and __fish_seen_subcommand_from workspace" -f -a "switch" -d 'Switch to specific workspace'
complete -c rift-cli -n "__fish_rift_cli_using_subcommand execute; and __fish_seen_subcommand_from workspace" -f -a "move-window" -d 'Move current window to workspace'
complete -c rift-cli -n "__fish_rift_cli_using_subcommand execute; and __fish_seen_subcommand_from workspace" -f -a "create" -d 'Create a new workspace'
complete -c rift-cli -n "__fish_rift_cli_using_subcommand execute; and __fish_seen_subcommand_from workspace" -f -a "last" -d 'Switch to the last workspace'
complete -c rift-cli -n "__fish_rift_cli_using_subcommand execute; and __fish_seen_subcommand_from workspace" -f -a "set-layout" -d 'Set layout mode for a workspace (or active workspace when omitted)'
complete -c rift-cli -n "__fish_rift_cli_using_subcommand execute; and __fish_seen_subcommand_from workspace" -f -a "help" -d 'Print this message or the help of the given subcommand(s)'
complete -c rift-cli -n "__fish_rift_cli_using_subcommand execute; and __fish_seen_subcommand_from layout" -s h -l help -d 'Print help'
complete -c rift-cli -n "__fish_rift_cli_using_subcommand execute; and __fish_seen_subcommand_from layout" -f -a "ascend" -d 'Move selection up the tree'
complete -c rift-cli -n "__fish_rift_cli_using_subcommand execute; and __fish_seen_subcommand_from layout" -f -a "descend" -d 'Move selection down the tree'
complete -c rift-cli -n "__fish_rift_cli_using_subcommand execute; and __fish_seen_subcommand_from layout" -f -a "move-node" -d 'Move the selected node in a direction'
complete -c rift-cli -n "__fish_rift_cli_using_subcommand execute; and __fish_seen_subcommand_from layout" -f -a "join-window" -d 'Join the selected window with neighbor in a direction'
complete -c rift-cli -n "__fish_rift_cli_using_subcommand execute; and __fish_seen_subcommand_from layout" -f -a "toggle-stack" -d 'Toggle stacked state for the selected container'
complete -c rift-cli -n "__fish_rift_cli_using_subcommand execute; and __fish_seen_subcommand_from layout" -f -a "toggle-orientation" -d 'Global orientation toggle that works consistently across layout modes (and between splits/stacks)'
complete -c rift-cli -n "__fish_rift_cli_using_subcommand execute; and __fish_seen_subcommand_from layout" -f -a "unjoin" -d 'Unjoin previously joined windows'
complete -c rift-cli -n "__fish_rift_cli_using_subcommand execute; and __fish_seen_subcommand_from layout" -f -a "toggle-focus-float" -d 'Toggle floating on the focused selection (tree focus)'
complete -c rift-cli -n "__fish_rift_cli_using_subcommand execute; and __fish_seen_subcommand_from layout" -f -a "adjust-master-ratio" -d 'Adjust master ratio by a delta (master/stack layout only)'
complete -c rift-cli -n "__fish_rift_cli_using_subcommand execute; and __fish_seen_subcommand_from layout" -f -a "adjust-master-count" -d 'Adjust master count by a delta (master/stack layout only)'
complete -c rift-cli -n "__fish_rift_cli_using_subcommand execute; and __fish_seen_subcommand_from layout" -f -a "promote-to-master" -d 'Promote the selected window into the master area (master/stack layout only)'
complete -c rift-cli -n "__fish_rift_cli_using_subcommand execute; and __fish_seen_subcommand_from layout" -f -a "swap-master-stack" -d 'Swap the first master with the first stack window (master/stack layout only)'
complete -c rift-cli -n "__fish_rift_cli_using_subcommand execute; and __fish_seen_subcommand_from layout" -f -a "swap-windows" -d 'Swap two windows by window id (`WindowId { pid: ..., idx: ... }`)'
complete -c rift-cli -n "__fish_rift_cli_using_subcommand execute; and __fish_seen_subcommand_from layout" -f -a "scroll-strip" -d 'Scroll the strip by a normalized delta (scrolling layout only)'
complete -c rift-cli -n "__fish_rift_cli_using_subcommand execute; and __fish_seen_subcommand_from layout" -f -a "snap-strip" -d 'Snap the strip to the nearest column boundary (scrolling layout only)'
complete -c rift-cli -n "__fish_rift_cli_using_subcommand execute; and __fish_seen_subcommand_from layout" -f -a "center-selection" -d 'Toggle centering of the selected column in scrolling layout. If invoked again on the same selection, centering is removed'
complete -c rift-cli -n "__fish_rift_cli_using_subcommand execute; and __fish_seen_subcommand_from layout" -f -a "help" -d 'Print this message or the help of the given subcommand(s)'
complete -c rift-cli -n "__fish_rift_cli_using_subcommand execute; and __fish_seen_subcommand_from config" -s h -l help -d 'Print help'
complete -c rift-cli -n "__fish_rift_cli_using_subcommand execute; and __fish_seen_subcommand_from config" -f -a "set-animate" -d 'Update animation settings'
complete -c rift-cli -n "__fish_rift_cli_using_subcommand execute; and __fish_seen_subcommand_from config" -f -a "set-animation-duration"
complete -c rift-cli -n "__fish_rift_cli_using_subcommand execute; and __fish_seen_subcommand_from config" -f -a "set-animation-fps"
complete -c rift-cli -n "__fish_rift_cli_using_subcommand execute; and __fish_seen_subcommand_from config" -f -a "set-animation-easing"
complete -c rift-cli -n "__fish_rift_cli_using_subcommand execute; and __fish_seen_subcommand_from config" -f -a "set-mouse-follows-focus" -d 'Update mouse settings'
complete -c rift-cli -n "__fish_rift_cli_using_subcommand execute; and __fish_seen_subcommand_from config" -f -a "set-mouse-hides-on-focus"
complete -c rift-cli -n "__fish_rift_cli_using_subcommand execute; and __fish_seen_subcommand_from config" -f -a "set-focus-follows-mouse"
complete -c rift-cli -n "__fish_rift_cli_using_subcommand execute; and __fish_seen_subcommand_from config" -f -a "set-stack-offset" -d 'Update layout settings'
complete -c rift-cli -n "__fish_rift_cli_using_subcommand execute; and __fish_seen_subcommand_from config" -f -a "set-stack-default-orientation" -d 'Set the default stack orientation behavior. Value should be one of: "perpendicular", "same", "horizontal", or "vertical"'
complete -c rift-cli -n "__fish_rift_cli_using_subcommand execute; and __fish_seen_subcommand_from config" -f -a "set-outer-gaps"
complete -c rift-cli -n "__fish_rift_cli_using_subcommand execute; and __fish_seen_subcommand_from config" -f -a "set-inner-gaps"
complete -c rift-cli -n "__fish_rift_cli_using_subcommand execute; and __fish_seen_subcommand_from config" -f -a "set-workspace-names" -d 'Update workspace settings'
complete -c rift-cli -n "__fish_rift_cli_using_subcommand execute; and __fish_seen_subcommand_from config" -f -a "set" -d 'Generic set: set an arbitrary config key (dot-separated path) to a JSON value. Example: rift-cli execute config set --key settings.animate --value true'
complete -c rift-cli -n "__fish_rift_cli_using_subcommand execute; and __fish_seen_subcommand_from config" -f -a "get" -d 'Get current config'
complete -c rift-cli -n "__fish_rift_cli_using_subcommand execute; and __fish_seen_subcommand_from config" -f -a "save" -d 'Save current config to file'
complete -c rift-cli -n "__fish_rift_cli_using_subcommand execute; and __fish_seen_subcommand_from config" -f -a "reload" -d 'Reload config from file'
complete -c rift-cli -n "__fish_rift_cli_using_subcommand execute; and __fish_seen_subcommand_from config" -f -a "help" -d 'Print this message or the help of the given subcommand(s)'
complete -c rift-cli -n "__fish_rift_cli_using_subcommand execute; and __fish_seen_subcommand_from mission-control" -s h -l help -d 'Print help'
complete -c rift-cli -n "__fish_rift_cli_using_subcommand execute; and __fish_seen_subcommand_from mission-control" -f -a "show-all" -d 'Show all workspaces in mission control'
complete -c rift-cli -n "__fish_rift_cli_using_subcommand execute; and __fish_seen_subcommand_from mission-control" -f -a "show-current" -d 'Show current workspace in mission control'
complete -c rift-cli -n "__fish_rift_cli_using_subcommand execute; and __fish_seen_subcommand_from mission-control" -f -a "dismiss" -d 'Dismiss mission control'
complete -c rift-cli -n "__fish_rift_cli_using_subcommand execute; and __fish_seen_subcommand_from mission-control" -f -a "help" -d 'Print this message or the help of the given subcommand(s)'
complete -c rift-cli -n "__fish_rift_cli_using_subcommand execute; and __fish_seen_subcommand_from display" -s h -l help -d 'Print help'
complete -c rift-cli -n "__fish_rift_cli_using_subcommand execute; and __fish_seen_subcommand_from display" -f -a "focus" -d 'Focus a display by direction, index, or UUID'
complete -c rift-cli -n "__fish_rift_cli_using_subcommand execute; and __fish_seen_subcommand_from display" -f -a "move-mouse-to-index" -d 'Move mouse cursor to a display by index (0-based)'
complete -c rift-cli -n "__fish_rift_cli_using_subcommand execute; and __fish_seen_subcommand_from display" -f -a "move-mouse-to-uuid" -d 'Move mouse cursor to a display by UUID'
complete -c rift-cli -n "__fish_rift_cli_using_subcommand execute; and __fish_seen_subcommand_from display" -f -a "move-window" -d 'Move a window to a display by direction, index, or UUID'
complete -c rift-cli -n "__fish_rift_cli_using_subcommand execute; and __fish_seen_subcommand_from display" -f -a "help" -d 'Print this message or the help of the given subcommand(s)'
complete -c rift-cli -n "__fish_rift_cli_using_subcommand execute; and __fish_seen_subcommand_from save-and-exit" -s h -l help -d 'Print help'
complete -c rift-cli -n "__fish_rift_cli_using_subcommand execute; and __fish_seen_subcommand_from debug" -s h -l help -d 'Print help'
complete -c rift-cli -n "__fish_rift_cli_using_subcommand execute; and __fish_seen_subcommand_from serialize" -s h -l help -d 'Print help'
complete -c rift-cli -n "__fish_rift_cli_using_subcommand execute; and __fish_seen_subcommand_from toggle-space-activated" -s h -l help -d 'Print help'
complete -c rift-cli -n "__fish_rift_cli_using_subcommand execute; and __fish_seen_subcommand_from show-timing" -s h -l help -d 'Print help'
complete -c rift-cli -n "__fish_rift_cli_using_subcommand execute; and __fish_seen_subcommand_from help" -f -a "window" -d 'Window management commands'
complete -c rift-cli -n "__fish_rift_cli_using_subcommand execute; and __fish_seen_subcommand_from help" -f -a "workspace" -d 'Virtual workspace commands'
complete -c rift-cli -n "__fish_rift_cli_using_subcommand execute; and __fish_seen_subcommand_from help" -f -a "layout" -d 'Layout commands'
complete -c rift-cli -n "__fish_rift_cli_using_subcommand execute; and __fish_seen_subcommand_from help" -f -a "config" -d 'Configuration management commands'
complete -c rift-cli -n "__fish_rift_cli_using_subcommand execute; and __fish_seen_subcommand_from help" -f -a "mission-control" -d 'Mission control commands'
complete -c rift-cli -n "__fish_rift_cli_using_subcommand execute; and __fish_seen_subcommand_from help" -f -a "display" -d 'Display/mouse commands'
complete -c rift-cli -n "__fish_rift_cli_using_subcommand execute; and __fish_seen_subcommand_from help" -f -a "save-and-exit" -d 'Save current state and exit rift'
complete -c rift-cli -n "__fish_rift_cli_using_subcommand execute; and __fish_seen_subcommand_from help" -f -a "debug" -d 'Print layout tree debugging output in the running rift instance'
complete -c rift-cli -n "__fish_rift_cli_using_subcommand execute; and __fish_seen_subcommand_from help" -f -a "serialize" -d 'Serialize and print runtime state'
complete -c rift-cli -n "__fish_rift_cli_using_subcommand execute; and __fish_seen_subcommand_from help" -f -a "toggle-space-activated" -d 'Toggle whether the current space is managed by rift'
complete -c rift-cli -n "__fish_rift_cli_using_subcommand execute; and __fish_seen_subcommand_from help" -f -a "show-timing" -d 'Show timing metrics'
complete -c rift-cli -n "__fish_rift_cli_using_subcommand execute; and __fish_seen_subcommand_from help" -f -a "help" -d 'Print this message or the help of the given subcommand(s)'
complete -c rift-cli -n "__fish_rift_cli_using_subcommand subscribe; and not __fish_seen_subcommand_from mach cli unsub-mach unsub-cli list-cli help" -s h -l help -d 'Print help'
complete -c rift-cli -n "__fish_rift_cli_using_subcommand subscribe; and not __fish_seen_subcommand_from mach cli unsub-mach unsub-cli list-cli help" -f -a "mach" -d 'Subscribe to Mach IPC events'
complete -c rift-cli -n "__fish_rift_cli_using_subcommand subscribe; and not __fish_seen_subcommand_from mach cli unsub-mach unsub-cli list-cli help" -f -a "cli" -d 'Subscribe to events via CLI command execution'
complete -c rift-cli -n "__fish_rift_cli_using_subcommand subscribe; and not __fish_seen_subcommand_from mach cli unsub-mach unsub-cli list-cli help" -f -a "unsub-mach" -d 'Unsubscribe from Mach IPC events'
complete -c rift-cli -n "__fish_rift_cli_using_subcommand subscribe; and not __fish_seen_subcommand_from mach cli unsub-mach unsub-cli list-cli help" -f -a "unsub-cli" -d 'Unsubscribe from CLI events'
complete -c rift-cli -n "__fish_rift_cli_using_subcommand subscribe; and not __fish_seen_subcommand_from mach cli unsub-mach unsub-cli list-cli help" -f -a "list-cli" -d 'List current CLI subscriptions'
complete -c rift-cli -n "__fish_rift_cli_using_subcommand subscribe; and not __fish_seen_subcommand_from mach cli unsub-mach unsub-cli list-cli help" -f -a "help" -d 'Print this message or the help of the given subcommand(s)'
complete -c rift-cli -n "__fish_rift_cli_using_subcommand subscribe; and __fish_seen_subcommand_from mach" -s h -l help -d 'Print help'
complete -c rift-cli -n "__fish_rift_cli_using_subcommand subscribe; and __fish_seen_subcommand_from cli" -l event -d 'Event to subscribe to (workspace_changed, windows_changed, window_title_changed, stacks_changed, *)' -r
complete -c rift-cli -n "__fish_rift_cli_using_subcommand subscribe; and __fish_seen_subcommand_from cli" -l command -d 'Command to execute when event occurs' -r
complete -c rift-cli -n "__fish_rift_cli_using_subcommand subscribe; and __fish_seen_subcommand_from cli" -l args -d 'Arguments to pass to command (event data will be appended as JSON)' -r
complete -c rift-cli -n "__fish_rift_cli_using_subcommand subscribe; and __fish_seen_subcommand_from cli" -s h -l help -d 'Print help'
complete -c rift-cli -n "__fish_rift_cli_using_subcommand subscribe; and __fish_seen_subcommand_from unsub-mach" -s h -l help -d 'Print help'
complete -c rift-cli -n "__fish_rift_cli_using_subcommand subscribe; and __fish_seen_subcommand_from unsub-cli" -s h -l help -d 'Print help'
complete -c rift-cli -n "__fish_rift_cli_using_subcommand subscribe; and __fish_seen_subcommand_from list-cli" -s h -l help -d 'Print help'
complete -c rift-cli -n "__fish_rift_cli_using_subcommand subscribe; and __fish_seen_subcommand_from help" -f -a "mach" -d 'Subscribe to Mach IPC events'
complete -c rift-cli -n "__fish_rift_cli_using_subcommand subscribe; and __fish_seen_subcommand_from help" -f -a "cli" -d 'Subscribe to events via CLI command execution'
complete -c rift-cli -n "__fish_rift_cli_using_subcommand subscribe; and __fish_seen_subcommand_from help" -f -a "unsub-mach" -d 'Unsubscribe from Mach IPC events'
complete -c rift-cli -n "__fish_rift_cli_using_subcommand subscribe; and __fish_seen_subcommand_from help" -f -a "unsub-cli" -d 'Unsubscribe from CLI events'
complete -c rift-cli -n "__fish_rift_cli_using_subcommand subscribe; and __fish_seen_subcommand_from help" -f -a "list-cli" -d 'List current CLI subscriptions'
complete -c rift-cli -n "__fish_rift_cli_using_subcommand subscribe; and __fish_seen_subcommand_from help" -f -a "help" -d 'Print this message or the help of the given subcommand(s)'
complete -c rift-cli -n "__fish_rift_cli_using_subcommand service; and not __fish_seen_subcommand_from install uninstall start stop restart help" -s h -l help -d 'Print help'
complete -c rift-cli -n "__fish_rift_cli_using_subcommand service; and not __fish_seen_subcommand_from install uninstall start stop restart help" -f -a "install" -d 'Install the per-user launchd service'
complete -c rift-cli -n "__fish_rift_cli_using_subcommand service; and not __fish_seen_subcommand_from install uninstall start stop restart help" -f -a "uninstall" -d 'Uninstall the per-user launchd service'
complete -c rift-cli -n "__fish_rift_cli_using_subcommand service; and not __fish_seen_subcommand_from install uninstall start stop restart help" -f -a "start" -d 'Start (or bootstrap) the service'
complete -c rift-cli -n "__fish_rift_cli_using_subcommand service; and not __fish_seen_subcommand_from install uninstall start stop restart help" -f -a "stop" -d 'Stop (or bootout/kill) the service'
complete -c rift-cli -n "__fish_rift_cli_using_subcommand service; and not __fish_seen_subcommand_from install uninstall start stop restart help" -f -a "restart" -d 'Restart the service (kickstart -k)'
complete -c rift-cli -n "__fish_rift_cli_using_subcommand service; and not __fish_seen_subcommand_from install uninstall start stop restart help" -f -a "help" -d 'Print this message or the help of the given subcommand(s)'
complete -c rift-cli -n "__fish_rift_cli_using_subcommand service; and __fish_seen_subcommand_from install" -s h -l help -d 'Print help'
complete -c rift-cli -n "__fish_rift_cli_using_subcommand service; and __fish_seen_subcommand_from uninstall" -s h -l help -d 'Print help'
complete -c rift-cli -n "__fish_rift_cli_using_subcommand service; and __fish_seen_subcommand_from start" -s h -l help -d 'Print help'
complete -c rift-cli -n "__fish_rift_cli_using_subcommand service; and __fish_seen_subcommand_from stop" -s h -l help -d 'Print help'
complete -c rift-cli -n "__fish_rift_cli_using_subcommand service; and __fish_seen_subcommand_from restart" -s h -l help -d 'Print help'
complete -c rift-cli -n "__fish_rift_cli_using_subcommand service; and __fish_seen_subcommand_from help" -f -a "install" -d 'Install the per-user launchd service'
complete -c rift-cli -n "__fish_rift_cli_using_subcommand service; and __fish_seen_subcommand_from help" -f -a "uninstall" -d 'Uninstall the per-user launchd service'
complete -c rift-cli -n "__fish_rift_cli_using_subcommand service; and __fish_seen_subcommand_from help" -f -a "start" -d 'Start (or bootstrap) the service'
complete -c rift-cli -n "__fish_rift_cli_using_subcommand service; and __fish_seen_subcommand_from help" -f -a "stop" -d 'Stop (or bootout/kill) the service'
complete -c rift-cli -n "__fish_rift_cli_using_subcommand service; and __fish_seen_subcommand_from help" -f -a "restart" -d 'Restart the service (kickstart -k)'
complete -c rift-cli -n "__fish_rift_cli_using_subcommand service; and __fish_seen_subcommand_from help" -f -a "help" -d 'Print this message or the help of the given subcommand(s)'
complete -c rift-cli -n "__fish_rift_cli_using_subcommand verify" -s h -l help -d 'Print help'
complete -c rift-cli -n "__fish_rift_cli_using_subcommand help; and not __fish_seen_subcommand_from query execute subscribe service verify help" -f -a "query" -d 'Query information from rift'
complete -c rift-cli -n "__fish_rift_cli_using_subcommand help; and not __fish_seen_subcommand_from query execute subscribe service verify help" -f -a "execute" -d 'Execute commands in rift'
complete -c rift-cli -n "__fish_rift_cli_using_subcommand help; and not __fish_seen_subcommand_from query execute subscribe service verify help" -f -a "subscribe" -d 'Event subscription commands'
complete -c rift-cli -n "__fish_rift_cli_using_subcommand help; and not __fish_seen_subcommand_from query execute subscribe service verify help" -f -a "service" -d 'Manage the launchd service for rift'
complete -c rift-cli -n "__fish_rift_cli_using_subcommand help; and not __fish_seen_subcommand_from query execute subscribe service verify help" -f -a "verify"
complete -c rift-cli -n "__fish_rift_cli_using_subcommand help; and not __fish_seen_subcommand_from query execute subscribe service verify help" -f -a "help" -d 'Print this message or the help of the given subcommand(s)'
complete -c rift-cli -n "__fish_rift_cli_using_subcommand help; and __fish_seen_subcommand_from query" -f -a "workspaces" -d 'List virtual workspaces (optionally for a specific MacOS space)'
complete -c rift-cli -n "__fish_rift_cli_using_subcommand help; and __fish_seen_subcommand_from query" -f -a "windows" -d 'List windows (optionally filtered by space)'
complete -c rift-cli -n "__fish_rift_cli_using_subcommand help; and __fish_seen_subcommand_from query" -f -a "displays" -d 'List connected displays'
complete -c rift-cli -n "__fish_rift_cli_using_subcommand help; and __fish_seen_subcommand_from query" -f -a "window" -d 'Get information about a specific window'
complete -c rift-cli -n "__fish_rift_cli_using_subcommand help; and __fish_seen_subcommand_from query" -f -a "applications" -d 'List running applications'
complete -c rift-cli -n "__fish_rift_cli_using_subcommand help; and __fish_seen_subcommand_from query" -f -a "layout" -d 'Get layout state for a space'
complete -c rift-cli -n "__fish_rift_cli_using_subcommand help; and __fish_seen_subcommand_from query" -f -a "workspace-layout" -d 'Get workspace layout-engine mode(s)'
complete -c rift-cli -n "__fish_rift_cli_using_subcommand help; and __fish_seen_subcommand_from query" -f -a "metrics" -d 'Get performance metrics'
complete -c rift-cli -n "__fish_rift_cli_using_subcommand help; and __fish_seen_subcommand_from execute" -f -a "window" -d 'Window management commands'
complete -c rift-cli -n "__fish_rift_cli_using_subcommand help; and __fish_seen_subcommand_from execute" -f -a "workspace" -d 'Virtual workspace commands'
complete -c rift-cli -n "__fish_rift_cli_using_subcommand help; and __fish_seen_subcommand_from execute" -f -a "layout" -d 'Layout commands'
complete -c rift-cli -n "__fish_rift_cli_using_subcommand help; and __fish_seen_subcommand_from execute" -f -a "config" -d 'Configuration management commands'
complete -c rift-cli -n "__fish_rift_cli_using_subcommand help; and __fish_seen_subcommand_from execute" -f -a "mission-control" -d 'Mission control commands'
complete -c rift-cli -n "__fish_rift_cli_using_subcommand help; and __fish_seen_subcommand_from execute" -f -a "display" -d 'Display/mouse commands'
complete -c rift-cli -n "__fish_rift_cli_using_subcommand help; and __fish_seen_subcommand_from execute" -f -a "save-and-exit" -d 'Save current state and exit rift'
complete -c rift-cli -n "__fish_rift_cli_using_subcommand help; and __fish_seen_subcommand_from execute" -f -a "debug" -d 'Print layout tree debugging output in the running rift instance'
complete -c rift-cli -n "__fish_rift_cli_using_subcommand help; and __fish_seen_subcommand_from execute" -f -a "serialize" -d 'Serialize and print runtime state'
complete -c rift-cli -n "__fish_rift_cli_using_subcommand help; and __fish_seen_subcommand_from execute" -f -a "toggle-space-activated" -d 'Toggle whether the current space is managed by rift'
complete -c rift-cli -n "__fish_rift_cli_using_subcommand help; and __fish_seen_subcommand_from execute" -f -a "show-timing" -d 'Show timing metrics'
complete -c rift-cli -n "__fish_rift_cli_using_subcommand help; and __fish_seen_subcommand_from subscribe" -f -a "mach" -d 'Subscribe to Mach IPC events'
complete -c rift-cli -n "__fish_rift_cli_using_subcommand help; and __fish_seen_subcommand_from subscribe" -f -a "cli" -d 'Subscribe to events via CLI command execution'
complete -c rift-cli -n "__fish_rift_cli_using_subcommand help; and __fish_seen_subcommand_from subscribe" -f -a "unsub-mach" -d 'Unsubscribe from Mach IPC events'
complete -c rift-cli -n "__fish_rift_cli_using_subcommand help; and __fish_seen_subcommand_from subscribe" -f -a "unsub-cli" -d 'Unsubscribe from CLI events'
complete -c rift-cli -n "__fish_rift_cli_using_subcommand help; and __fish_seen_subcommand_from subscribe" -f -a "list-cli" -d 'List current CLI subscriptions'
complete -c rift-cli -n "__fish_rift_cli_using_subcommand help; and __fish_seen_subcommand_from service" -f -a "install" -d 'Install the per-user launchd service'
complete -c rift-cli -n "__fish_rift_cli_using_subcommand help; and __fish_seen_subcommand_from service" -f -a "uninstall" -d 'Uninstall the per-user launchd service'
complete -c rift-cli -n "__fish_rift_cli_using_subcommand help; and __fish_seen_subcommand_from service" -f -a "start" -d 'Start (or bootstrap) the service'
complete -c rift-cli -n "__fish_rift_cli_using_subcommand help; and __fish_seen_subcommand_from service" -f -a "stop" -d 'Stop (or bootout/kill) the service'
complete -c rift-cli -n "__fish_rift_cli_using_subcommand help; and __fish_seen_subcommand_from service" -f -a "restart" -d 'Restart the service (kickstart -k)'
